CREATE TABLE IF NOT EXISTS (
    SESSION_ID INTEGER,
    WINDOW_ID INTEGER,
    PRIMARY KEY(SESSION_ID, WINDOW_ID),
    FOREIGN KEY(SESSION_ID) REFERENCES SESSIONS(ID),
    FOREIGN KEY(WINDOW_ID) REFERENCES WINDOWS(ID)
)
